// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiaFhexZKlLDLeBGVAGElu_PoWhxOgqYo',
    appId: '1:105314876063:web:69b3e75effa3f72cad00aa',
    messagingSenderId: '105314876063',
    projectId: 'polleria-2e40a',
    authDomain: 'polleria-2e40a.firebaseapp.com',
    storageBucket: 'polleria-2e40a.firebasestorage.app',
    measurementId: 'G-FVQJLCELR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxaEbuV4Y2OGWfmFK8Z-qr5psiDOLE6O0',
    appId: '1:105314876063:android:7a8f38983de0fdecad00aa',
    messagingSenderId: '105314876063',
    projectId: 'polleria-2e40a',
    storageBucket: 'polleria-2e40a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_97fCb_gjvoMeibqIxky9caCObr-0yM',
    appId: '1:105314876063:ios:83d694f828b54b0ead00aa',
    messagingSenderId: '105314876063',
    projectId: 'polleria-2e40a',
    storageBucket: 'polleria-2e40a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-_97fCb_gjvoMeibqIxky9caCObr-0yM',
    appId: '1:105314876063:ios:83d694f828b54b0ead00aa',
    messagingSenderId: '105314876063',
    projectId: 'polleria-2e40a',
    storageBucket: 'polleria-2e40a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiaFhexZKlLDLeBGVAGElu_PoWhxOgqYo',
    appId: '1:105314876063:web:c83cdc8706119f63ad00aa',
    messagingSenderId: '105314876063',
    projectId: 'polleria-2e40a',
    authDomain: 'polleria-2e40a.firebaseapp.com',
    storageBucket: 'polleria-2e40a.firebasestorage.app',
    measurementId: 'G-74TWCYWC5M',
  );
}